---
output:
  pdf_document: default
  html_document: default
---

Downloading packages and reading the data 
```{r,warning=FALSE}
library(data.table)
library(effects)
library(cowplot)
library(gridExtra)
library(grid)
library(ggplot2)
library(lattice)
library(ggpubr)
library(effects)
library(stargazer)
library(purrr)
library(plm)
library(data.table)
library(bit64)
options(scipen = 999)
library(knitr)
library(broom)
library(tseries) # for `adf.test()`
library(dynlm) #for function `dynlm()`
library(vars) # for function `VAR()`
library(nlWaldTest) # for the `nlWaldtest()` function
library(lmtest) #for `coeftest()` and `bptest()`.
library(car) #for `hccm()` robust standard errors
library(sandwich)
library(knitr) #for `kable()`
library(forecast) 
library(systemfit)
library(AER)
library(xtable)
library(jtools)
library(devtools)
library(interactions)
library(ggplot2)
library(sjPlot)
library(sjmisc)

# reading and sorting the data. 
block_1_1<-read.csv("Block_1.csv")
block_2_1<-read.csv("Block_2.csv")
block_8_1<-read.csv("Block_8.csv")
block_9_1<-read.csv("Block_9.csv")

block_1_1$block<-"1"
block_1_1$type<-"old"
block_2_1$block<-"2"
block_2_1$type<-"old"
block_8_1$block<-"8"
block_9_1$block<-"9"
block_8_1$type<-"new"
block_9_1$type<-"new"



block_1_2<-read.csv("Block_1_2.csv")
block_2_2<-read.csv("Block_2_2.csv")
block_8_2<-read.csv("Block_8_2.csv")
block_9_2<-read.csv("Block_9_2.csv")



block_1_2$block<-"1"
block_2_2$block<-"2"
block_1_2$type<-"old"
block_2_2$type<-"old"
block_8_2$block<-"8"
block_9_2$block<-"9"
block_8_2$type<-"new"
block_9_2$type<-"new"

data<-rbind(block_1_1,block_1_2,block_2_1,block_2_2,block_8_1,block_8_2,block_9_1,block_9_2)
data$Date <- as.Date(data$Date , "%d/%m/%Y") # converting to date format 

# insert time before/after intervention True/False

df1<-data[data$Date<="2021-09-20",]
df1<-df1[df1$Date>="2020-03-10",]
dates<-unique(df1$Date)
`%!in%` <- Negate(`%in%`)
df2<-data[data$Date %!in% dates,]
df1$covid<-TRUE
df2$covid<-FALSE

data<-rbind(df1,df2)

df1<-data[data$Date>="2022-03-21",]
df1$intervention<-paste("After intervention",df1$block, sep = " ", collapse = NULL)
df2<-data[data$Date<"2022-03-21",]
df2$intervention<-"Before intervention"

data<-rbind(df1,df2)
data$intervention<- factor(data$intervention, levels = c("Before intervention", "After intervention 1","After intervention 2","After intervention 8","After intervention 9"))
data$block<-as.character(data$block)
```


Figure 1 plot
```{r}
d<-data.frame(date=as.Date("21/03/2022","%d/%m/%Y"),event="Intervention Starts")
d2<-data.frame(date=as.Date("01/01/2021","%d/%m/%Y"),event="Residential Halls impacted\n due to COVID-19")
ggplot(data,aes(x=Date,y=PeriodValue))+geom_line(aes(color=block))+geom_vline(data=d, mapping=aes(xintercept=date), color="blue",size=0.5)+geom_text(data=d, mapping=aes(x=date, y=23, label=event), size=3.5, angle=90, vjust=-0.4, hjust=0)+scale_x_date(date_breaks = "months" , date_labels = "%b-%y")+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5,size=9))+annotate("rect", xmin=as.Date("10/03/2020","%d/%m/%Y"), xmax=as.Date("20/09/2021","%d/%m/%Y"), ymin=0, ymax=Inf, alpha=0.15, fill="red")+geom_text(data=d2, mapping=aes(x=date, y=25, label=event), size=4)+ylab( expression ("Water Consumption in "~m^3))
```

fixed-effects model
```{r}
model <- plm((PeriodValue)~intervention+covid,data = data,index = c("block","Date"), model="within",effects="twoways")
summary(model)
```
Summary 
```{r}
stargazer(model, type = "text",add.lines=list(c("Between R2",round(r.squared(update(model, effect = "individual", model = "between")), 3))))
```


Testing for best model (OLS vs fixed vs pooled)
Testing for the prescence of random or fixed effects. 
```{r}
pooled_model <- plm((PeriodValue)~intervention+covid,data = data,index = c("block","Date"), model="pooling",effects="twoways")
fixed_model <- plm((PeriodValue)~intervention+covid,data = data,index = c("block","Date"), model="within",effects="twoways")
random_model <- plm((PeriodValue)~intervention+covid,data = data,index = c("block","Date"), model="random",random.method = "walhus",effects="twoways")

pFtest(fixed_model, pooled_model) # REJECT POOLED MODEL
## Test for fixed vs random effects  
phtest(fixed_model, random_model) # fixed model is better
## Test for pooled vs random effects
plmtest(pooled_model, type=c("bp"))

plmtest(fixed_model, c("time"), type=("bp"))
```

testing for multi-collinearity assumption
```{r}
vif(lm((PeriodValue~intervention+covid+block),data=data))
```
